Vagrant.configure(2) do |config|
    # image Ubuntu 
    config.vm.box = "bento/ubuntu-22.04"
    # don't check this repository for updates
    config.vm.box_check_update = false
    config.vm.provision "shell", path: "script.sh"
  
    config.vm.provider "virtualbox" do |vb|
      # name VM
      vb.name = "vm1"
      # volume RAM
      vb.memory = 2048
      # count of processor cores
      vb.cpus = 2
    end
    
    # hostname VM
    config.vm.hostname = "vm1"
    config.vm.network "public_network", ip: "192.168.0.132", bridge: "Intel(R) Wireless-AC 9462"
end