Vagrant.configure(2) do |config|
    # image centos/7
    config.vm.box = "centos/7"
    # don't check this repository for updates
    config.vm.box_check_update = false
  
    # FIRST VM
    config.vm.define "vm1" do |subconfig|
      # name VM
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "vm1"
      end
      # hostname VM
      subconfig.vm.hostname = "vm1"
      # config network
      subconfig.vm.network "public_network", ip: "192.168.0.117", bridge: "Intel(R) Wireless-AC 9462"
      # install packages
      subconfig.vm.provision "tools", type: "shell", inline: "sudo yum -y install vim htop mc tree net-tools"
    end
  
    # SECOND VM
    config.vm.define "vm2" do |subconfig|
      # name VM
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "vm2"
      end
      # hostname VM
      subconfig.vm.hostname = "vm2"
      # config network
      subconfig.vm.network "public_network", ip: "192.168.0.118", bridge: "Intel(R) Wireless-AC 9462"
      # install packages
      subconfig.vm.provision "tools", type: "shell", inline: "sudo yum -y install vim htop mc tree net-tools"
    end
    
    # update system (first and second VM)
    config.vm.provision "update", type: "shell", inline: "sudo yum -y update"
end